In [5]:
# Importations

import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import sys
sys.path.append("../SRC")

import importlib
import sp_cleaning_aviation as sp

importlib.reload(sp)

pd.set_option("display.max_columns", None)

In [6]:
final_df = pd.read_csv('../data/joint_dataset.csv')

/var/folders/r8/sbs1vswj5qb9kjwlkhpfxj4c0000gn/T/ipykernel_55436/1970956837.py:1: DtypeWarning: Columns (7,8,33,34,35,36,37,40,41,42,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  final_df = pd.read_csv('../data/joint_dataset.csv')

In [7]:
# A copy of the joint dataset is created to implement the changes

aviation_df = final_df.copy()

In [8]:
sp.preliminary_eda(aviation_df)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE_x,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,IATA_CODE,AIRLINE_NAME,IATA_CODE_ORIGIN,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE,IATA_CODE_DEST,AIRPORT_DEST,CITY_DEST,STATE_DEST,COUNTRY_DEST,LATITUDE_DEST,LONGITUDE_DEST
4690018,2015,10,20,2,WN,192,N904WN,13495,15304,925,952.0,27.0,10.0,1002.0,90.0,80.0,67.0,488,1209.0,3.0,1155,1212.0,17.0,0,0,NaN,0.0,0.0,17.0,0.0,0.0,WN,Southwest Airlines Co.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5263975,2015,11,25,3,DL,1273,N921DN,ATL,JAX,1926,1925.0,-1.0,13.0,1938.0,70.0,62.0,43.0,270,2021.0,6.0,2036,2027.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,DL,Delta Air Lines Inc.,ATL,Hartsfield-Jackson Atlanta International Airport,Atlanta,GA,USA,33.64044,-84.42694,JAX,Jacksonville International Airport,Jacksonville,FL,USA,30.49406,-81.68786
4594500,2015,10,14,3,WN,1161,N743SW,14683,12191,840,837.0,-3.0,26.0,903.0,60.0,66.0,36.0,192,939.0,4.0,940,943.0,3.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,WN,Southwest Airlines Co.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5148630,2015,11,18,3,WN,2314,N927WN,FLL,PVD,1245,1305.0,20.0,15.0,1320.0,180.0,176.0,157.0,1188,1557.0,4.0,1545,1601.0,16.0,0,0,NaN,0.0,0.0,3.0,13.0,0.0,WN,Southwest Airlines Co.,FLL,Fort Lauderdale-Hollywood International Airport,Ft. Lauderdale,FL,USA,26.07258,-80.15275,PVD,Theodore Francis Green State Airport,Providence,RI,USA,41.72400,-71.42822
3750908,2015,8,21,5,OO,4680,N187PQ,SLC,EUG,1105,1213.0,68.0,9.0,1222.0,119.0,NaN,NaN,618,1431.0,3.0,1204,1434.0,NaN,1,0,NaN,NaN,NaN,NaN,NaN,NaN,OO,Skywest Airlines Inc.,SLC,Salt Lake City International Airport,Salt Lake City,UT,USA,40.78839,-111.97777,EUG,Eugene Airport (Mahlon Sweet Field),Eugene,OR,USA,44.12326,-123.21869

----------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 47 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE_x            object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
 31  IATA_CODE            object
 32  AIRLINE_NAME         object
 33  IATA_CODE_ORIGIN     object
 34  AIRPORT              object
 35  CITY                 object
 36  STATE                object
 37  COUNTRY              object
 38  LATITUDE             float64
 39  LONGITUDE            float64
 40  IATA_CODE_DEST       object
 41  AIRPORT_DEST         object
 42  CITY_DEST            object
 43  STATE_DEST           object
 44  COUNTRY_DEST         object
 45  LATITUDE_DEST        float64
 46  LONGITUDE_DEST       float64
dtypes: float64(20), int64(10), object(17)
memory usage: 2.0+ GB

None

----------------
NULL

YEAR                    0.00
MONTH                   0.00
DAY                     0.00
DAY_OF_WEEK             0.00
AIRLINE_x               0.00
FLIGHT_NUMBER           0.00
TAIL_NUMBER             0.25
ORIGIN_AIRPORT          0.00
DESTINATION_AIRPORT     0.00
SCHEDULED_DEPARTURE     0.00
DEPARTURE_TIME          1.48
DEPARTURE_DELAY         1.48
TAXI_OUT                1.53
WHEELS_OFF              1.53
SCHEDULED_TIME          0.00
ELAPSED_TIME            1.81
AIR_TIME                1.81
DISTANCE                0.00
WHEELS_ON               1.59
TAXI_IN                 1.59
SCHEDULED_ARRIVAL       0.00
ARRIVAL_TIME            1.59
ARRIVAL_DELAY           1.81
DIVERTED                0.00
CANCELLED               0.00
CANCELLATION_REASON    98.46
AIR_SYSTEM_DELAY       81.72
SECURITY_DELAY         81.72
AIRLINE_DELAY          81.72
LATE_AIRCRAFT_DELAY    81.72
WEATHER_DELAY          81.72
IATA_CODE               0.00
AIRLINE_NAME            0.00
IATA_CODE_ORIGIN        8.35
AIRPORT                 8.35
CITY                    8.35
STATE                   8.35
COUNTRY                 8.35
LATITUDE                8.43
LONGITUDE               8.43
IATA_CODE_DEST          8.35
AIRPORT_DEST            8.35
CITY_DEST               8.35
STATE_DEST              8.35
COUNTRY_DEST            8.35
LATITUDE_DEST           8.43
LONGITUDE_DEST          8.43
dtype: float64

----------------
DUPLICATES
0
----------------
VALUE COUNTS
AIRLINE_x
WN    1261855
DL     875881
AA     725984
OO     588353
EV     571977
UA     515723
MQ     294632
B6     267048
US     198715
AS     172521
NK     117379
F9      90836
HA      76272
VX      61903
Name: count, dtype: int64
---------------------------
TAIL_NUMBER
N480HA    3768
N488HA    3723
N484HA    3723
N493HA    3585
N478HA    3577
          ...
N175UA       1
N852NW       1
N7LBAA       1
N7LEAA       1
N180UA       1
Name: count, Length: 4897, dtype: int64
---------------------------
ORIGIN_AIRPORT
ATL      346836
ORD      285884
DFW      239551
DEN      196055
LAX      194673
          ...
11577         1
13127         1
12511         1
12177         1
13344         1
Name: count, Length: 924, dtype: int64
---------------------------
DESTINATION_AIRPORT
ATL      346904
ORD      285906
DFW      239582
DEN      196010
LAX      194696
          ...
15041         1
12177         1
10918         1
13127         1
10779         1
Name: count, Length: 920, dtype: int64
---------------------------
CANCELLATION_REASON
B    48851
A    25262
C    15749
D       22
Name: count, dtype: int64
---------------------------
IATA_CODE
WN    1261855
DL     875881
AA     725984
OO     588353
EV     571977
UA     515723
MQ     294632
B6     267048
US     198715
AS     172521
NK     117379
F9      90836
HA      76272
VX      61903
Name: count, dtype: int64
---------------------------
AIRLINE_NAME
Southwest Airlines Co.          1261855
Delta Air Lines Inc.             875881
American Airlines Inc.           725984
Skywest Airlines Inc.            588353
Atlantic Southeast Airlines      571977
United Air Lines Inc.            515723
American Eagle Airlines Inc.     294632
JetBlue Airways                  267048
US Airways Inc.                  198715
Alaska Airlines Inc.             172521
Spirit Air Lines                 117379
Frontier Airlines Inc.            90836
Hawaiian Airlines Inc.            76272
Virgin America                    61903
Name: count, dtype: int64
---------------------------
IATA_CODE_ORIGIN
ATL    346836
ORD    285884
DFW    239551
DEN    196055
LAX    194673
        ...
HYA        83
DLG        77
GST        77
AKN        63
ITH        34
Name: count, Length: 322, dtype: int64
---------------------------
AIRPORT
Hartsfield-Jackson Atlanta International Airport    346836
Chicago O'Hare International Airport                285884
Dallas/Fort Worth International Airport             239551
Denver International Airport                        196055
Los Angeles International Airport                   194673
                                                     ...
Barnstable Municipal Airport                            83
Dillingham Airport                                      77
Gustavus Airport                                        77
King Salmon Airport                                     63
Ithaca Tompkins Regional Airport                        34
Name: count, Length: 322, dtype: int64
---------------------------
CITY
Chicago              366770
Atlanta              346836
Dallas-Fort Worth    239551
Houston              198664
Denver               196055
                      ...
Hyannis                  83
Dillingham               77
Gustavus                 77
King Salmon              63
Ithaca                   34
Name: count, Length: 308, dtype: int64
---------------------------
STATE
CA    647911
TX    631124
FL    415586
IL    381644
GA    360496
NY    246235
CO    215451
AZ    165469
NC    146906
NV    146723
VA    138577
MI    137033
WA    123548
MN    118701
MA    109290
NJ    108174
PA     99995
UT     99972
MO     93838
HI     91181
MD     86079
TN     75443
OH     74514
LA     65185
OR     55620
WI     51376
IN     39107
KY     36880
AK     33300
OK     31445
SC     28341
PR     26748
AL     26482
AR     22654
NM     22241
NE     20023
CT     18799
IA     17382
ID     16915
ND     16530
MT     14848
MS     13109
RI     11058
KS     10966
SD      9267
WY      8218
NH      6292
VI      5287
ME      5047
VT      2978
WV      2385
GU       334
AS       107
DE       100
Name: count, dtype: int64
---------------------------
COUNTRY
USA    5332914
Name: count, dtype: int64
---------------------------
IATA_CODE_DEST
ATL    346904
ORD    285906
DFW    239582
DEN    196010
LAX    194696
        ...
STC        82
DLG        77
GST        77
AKN        63
ITH        35
Name: count, Length: 322, dtype: int64
---------------------------
AIRPORT_DEST
Hartsfield-Jackson Atlanta International Airport    346904
Chicago O'Hare International Airport                285906
Dallas/Fort Worth International Airport             239582
Denver International Airport                        196010
Los Angeles International Airport                   194696
                                                     ...
St. Cloud Regional Airport                              82
Dillingham Airport                                      77
Gustavus Airport                                        77
King Salmon Airport                                     63
Ithaca Tompkins Regional Airport                        35
Name: count, Length: 322, dtype: int64
---------------------------
CITY_DEST
Chicago              366790
Atlanta              346904
Dallas-Fort Worth    239582
Houston              198724
Denver               196010
                      ...
St Cloud                 82
Dillingham               77
Gustavus                 77
King Salmon              63
Ithaca                   35
Name: count, Length: 308, dtype: int64
---------------------------
STATE_DEST
CA    647899
TX    631214
FL    415554
IL    381666
GA    360563
NY    246231
CO    215404
AZ    165466
NC    146906
NV    146739
VA    138558
MI    136928
WA    123557
MN    118713
MA    109299
NJ    108237
PA    100000
UT     99955
MO     93828
HI     91176
MD     86085
TN     75434
OH     74494
LA     65184
OR     55611
WI     51381
IN     39104
KY     36874
AK     33299
OK     31447
SC     28339
PR     26747
AL     26484
AR     22647
NM     22234
NE     20023
CT     18797
IA     17387
ID     16918
ND     16535
MT     14852
MS     13110
RI     11059
KS     10966
SD      9269
WY      8214
NH      6292
VI      5286
ME      5048
VT      2976
WV      2386
GU       334
AS       107
DE        98
Name: count, dtype: int64
---------------------------
COUNTRY_DEST
USA    5332914
Name: count, dtype: int64
---------------------------

In [9]:
# Drop redundant or non-informative columns

cols_to_drop = [
    "AIRLINE_x", # duplicate of AIRLINE_NAME
    "IATA_CODE", # redundant airline code
    "IATA_CODE_ORIGIN", # redundant origin airport code
    "IATA_CODE_DEST", # redundant destination airport code
    "COUNTRY", # all USA, not informative
    "COUNTRY_DEST" # all USA, not informative
]

aviation_df = aviation_df.drop(columns=cols_to_drop)

In [10]:
# Rename columns for symmetry and clarity

aviation_df.rename(columns={
    "CITY": "CITY_ORIGIN",
    "STATE": "STATE_ORIGIN",
    "AIRPORT": "AIRPORT_ORIGIN"
}, inplace=True)

In [11]:
# Fill missing values in numeric columns with 0

numeric_cols_zero_fill = [
    "DEPARTURE_DELAY", "ARRIVAL_DELAY", "TAXI_OUT", "TAXI_IN", 
    "AIR_TIME", "WHEELS_OFF", "WHEELS_ON",
    "AIR_SYSTEM_DELAY", "SECURITY_DELAY", "AIRLINE_DELAY",
    "LATE_AIRCRAFT_DELAY", "WEATHER_DELAY",
    "DEPARTURE_TIME", "ARRIVAL_TIME", "ELAPSED_TIME"
]

sp.zero_fill(aviation_df, numeric_cols_zero_fill)

print(aviation_df[numeric_cols_zero_fill].isna().sum())

DEPARTURE_DELAY        0
ARRIVAL_DELAY          0
TAXI_OUT               0
TAXI_IN                0
AIR_TIME               0
WHEELS_OFF             0
WHEELS_ON              0
AIR_SYSTEM_DELAY       0
SECURITY_DELAY         0
AIRLINE_DELAY          0
LATE_AIRCRAFT_DELAY    0
WEATHER_DELAY          0
DEPARTURE_TIME         0
ARRIVAL_TIME           0
ELAPSED_TIME           0
dtype: int64

In [12]:
# Fill missing values in categorical columns with "UNKNOWN"

categorical_cols_unknown_fill = [
    "TAIL_NUMBER",
    "STATE_ORIGIN", "STATE_DEST", "CITY_ORIGIN", "CITY_DEST",
    "AIRPORT_ORIGIN", "AIRPORT_DEST"
]

sp.fill_unknown(aviation_df, categorical_cols_unknown_fill)

print(aviation_df[categorical_cols_unknown_fill].isna().sum())

TAIL_NUMBER       0
STATE_ORIGIN      0
STATE_DEST        0
CITY_ORIGIN       0
CITY_DEST         0
AIRPORT_ORIGIN    0
AIRPORT_DEST      0
dtype: int64

In [13]:
# Fill missing values for "CANCELLATION_REASON" with "None"

aviation_df["CANCELLATION_REASON"] = aviation_df["CANCELLATION_REASON"].fillna("None")

In [14]:
# Delay flags

# The aim is to convert continuous delay times into categorical flags that are easier to analyze

aviation_df["DELAYED"] = np.where(aviation_df["ARRIVAL_DELAY"] > 15, 1, 0) # DELAYED = 1 if the flight arrived more than 15 minutes late, otherwise 0.
aviation_df["EXTREME_DELAY"] = np.where(aviation_df["ARRIVAL_DELAY"] > 60, 1, 0) # EXTREME_DELAY = 1 if the flight arrived more than 60 minutes late, otherwise 0.

# This will help us identify outliers or severe disruptions.

In [15]:
# Flight duration in hours

# Converting flight times from minutes to hours to make it more intuitive for analysis and easier to compare flight durations. 

aviation_df["AIR_TIME_HOURS"] = aviation_df["AIR_TIME"] / 60
aviation_df["SCHEDULED_TIME_HOURS"] = aviation_df["SCHEDULED_TIME"] / 60

aviation_df["AIR_TIME_HOURS"] = aviation_df["AIR_TIME_HOURS"].round(2)
aviation_df["SCHEDULED_TIME_HOURS"] = aviation_df["SCHEDULED_TIME_HOURS"].round(2)

In [16]:
# Route feature

# Creation of a single string representing the flight route

aviation_df["ROUTE"] = aviation_df["CITY_ORIGIN"].astype(str) + "-" + aviation_df["CITY_DEST"].astype(str)

In [17]:
# Date features

# Combination of year, month and day into a single datetime object to help filter.
# Extraction of the day of the week as a string to analyze patterns.
# Extraction of the month name to help detect seasonal trends.

aviation_df["DATE"] = pd.to_datetime(aviation_df[['YEAR', 'MONTH', 'DAY']])
aviation_df["WEEKDAY"] = aviation_df["DATE"].dt.day_name()
aviation_df["MONTH_NAME"] = aviation_df["DATE"].dt.month_name()

In [18]:
# Clean string values

# Removing unnecessary leading or trailing whitespace from strings and converting all letters to uppercase for "TAIL_NUMBER"

aviation_df["AIRLINE_NAME"] = aviation_df["AIRLINE_NAME"].str.strip()
aviation_df["TAIL_NUMBER"] = aviation_df["TAIL_NUMBER"].str.upper()

In [19]:
# Drop coordinates columns

coords_cols = ["LATITUDE", "LONGITUDE", "LATITUDE_DEST", "LONGITUDE_DEST"]
aviation_df = aviation_df.drop(columns=coords_cols)

In [20]:
# Fill missing values in scheduled time columns with median

scheduled_cols = ["SCHEDULED_TIME", "SCHEDULED_TIME_HOURS"]
for col in scheduled_cols:
    median_val = aviation_df[col].median()
    aviation_df[col].fillna(median_val, inplace=True)

/var/folders/r8/sbs1vswj5qb9kjwlkhpfxj4c0000gn/T/ipykernel_55436/4008098888.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  aviation_df[col].fillna(median_val, inplace=True)
/var/folders/r8/sbs1vswj5qb9kjwlkhpfxj4c0000gn/T/ipykernel_55436/4008098888.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  aviation_df[col].fillna(median_val, inplace=True)

In [21]:
# Ordenamos columnas para facilitar lectura del documento

cols_order = [
    "DATE", "YEAR", "MONTH", "DAY", "DAY_OF_WEEK", "WEEKDAY", "MONTH_NAME",
    "AIRLINE_NAME", "TAIL_NUMBER", "FLIGHT_NUMBER",
    "ORIGIN_AIRPORT", "DESTINATION_AIRPORT", 
    "SCHEDULED_DEPARTURE", "DEPARTURE_TIME", "DEPARTURE_DELAY", "TAXI_OUT", "WHEELS_OFF",
    "SCHEDULED_TIME", "SCHEDULED_TIME_HOURS", "ELAPSED_TIME", "AIR_TIME", "AIR_TIME_HOURS",
    "WHEELS_ON", "TAXI_IN", "ARRIVAL_TIME", "ARRIVAL_DELAY",
    "DELAYED", "EXTREME_DELAY",
    "CANCELLED", "DIVERTED", "CANCELLATION_REASON",
    "AIR_SYSTEM_DELAY", "SECURITY_DELAY", "AIRLINE_DELAY", "LATE_AIRCRAFT_DELAY", "WEATHER_DELAY",
    "AIRPORT_ORIGIN", "CITY_ORIGIN", "STATE_ORIGIN", "AIRPORT_DEST", "CITY_DEST", "STATE_DEST", "ROUTE"
]

aviation_df = aviation_df[cols_order]

In [22]:
# Eliminamos las columnas redundantes para nuestro análisis

aviation_df.drop(columns=["DAY_OF_WEEK", "MONTH", "ORIGIN_AIRPORT", "DESTINATION_AIRPORT"], inplace=True)

In [23]:
# Fixing all arrival-related and flight-execution fields for the cancelled flight. If the event did not occur, the values should be NaN (Not a Number).

aviation_df.loc[
    aviation_df["CANCELLED"] == 1,
    [
        "ARRIVAL_DELAY",
        "AIR_TIME",
        "AIR_TIME_HOURS",
        "ELAPSED_TIME",
        "WHEELS_ON",
        "ARRIVAL_TIME",
        "TAXI_IN"
    ]
] = np.nan

In [24]:
aviation_df.loc[
    aviation_df["CANCELLED"] == 1,
    ["DELAYED", "EXTREME_DELAY"]
] = np.nan

In [25]:
# For the diverted flights, we are going to treat them like the cancelled flight as the plane didn't arrive at the chosen destination. 

aviation_df.loc[
    aviation_df["DIVERTED"] == 1,
    [
        "ARRIVAL_DELAY",
        "ARRIVAL_TIME",
        "DELAYED",
        "EXTREME_DELAY"
    ]
] = np.nan

In [26]:
aviation_df.loc[
    aviation_df["DIVERTED"] == 1,
    ["DELAYED", "EXTREME_DELAY"]
] = np.nan

In [27]:
aviation_df.loc[aviation_df["CANCELLED"] == 1, ["DEPARTURE_TIME", "ARRIVAL_TIME"]] = np.nan

In [28]:
hhmm_cols = ["SCHEDULED_DEPARTURE", "DEPARTURE_TIME", "ARRIVAL_TIME"]
sp.hhmm_to_str_inplace(aviation_df, hhmm_cols)

aviation_df[hhmm_cols].head()

  SCHEDULED_DEPARTURE DEPARTURE_TIME ARRIVAL_TIME
0               00h05          23h54        04h08
1               00h10          00h02        07h41
2               00h20          00h18        08h11
3               00h20          00h15        07h56
4               00h25          00h24        02h59

In [33]:
aviation_df.sample(5)

,DATE,YEAR,DAY,WEEKDAY,MONTH_NAME,AIRLINE_NAME,TAIL_NUMBER,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,SCHEDULED_TIME_HOURS,ELAPSED_TIME,AIR_TIME,AIR_TIME_HOURS,WHEELS_ON,TAXI_IN,ARRIVAL_TIME,ARRIVAL_DELAY,DELAYED,EXTREME_DELAY,CANCELLED,DIVERTED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRPORT_ORIGIN,CITY_ORIGIN,STATE_ORIGIN,AIRPORT_DEST,CITY_DEST,STATE_DEST,ROUTE
1314319,2015-03-26,2015,26,Thursday,March,Southwest Airlines Co.,N7731A,200,13h40,13h40,0.0,15.0,1355.0,195.0,3.25,205.0,186.0,3.10,1901.0,4.0,19h05,10.0,0.0,0.0,0,0,None,0.0,0.0,0.0,0.0,0.0,Phoenix Sky Harbor International Airport,Phoenix,AZ,Chicago Midway International Airport,Chicago,IL,Phoenix-Chicago
552192,2015-02-06,2015,6,Friday,February,US Airways Inc.,N959UW,1773,11h30,11h28,-2.0,15.0,1143.0,237.0,3.95,208.0,185.0,3.08,1348.0,8.0,13h56,-31.0,0.0,0.0,0,0,None,0.0,0.0,0.0,0.0,0.0,Philadelphia International Airport,Philadelphia,PA,George Bush Intercontinental Airport,Houston,TX,Philadelphia-Houston
5805826,2015-12-30,2015,30,Wednesday,December,JetBlue Airways,N629JB,1389,23h15,23h33,18.0,14.0,2347.0,225.0,3.75,218.0,200.0,3.33,407.0,4.0,04h11,11.0,0.0,0.0,0,0,None,0.0,0.0,0.0,0.0,0.0,Newark Liberty International Airport,Newark,NJ,Luis Muñoz Marín International Airport,San Juan,PR,Newark-San Juan
5770108,2015-12-28,2015,28,Monday,December,Skywest Airlines Inc.,N613SK,4792,18h20,18h13,-7.0,21.0,1834.0,53.0,0.88,60.0,33.0,0.55,1907.0,6.0,19h13,0.0,0.0,0.0,0,0,None,0.0,0.0,0.0,0.0,0.0,Seattle-Tacoma International Airport,Seattle,WA,Portland International Airport,Portland,OR,Seattle-Portland
2862162,2015-06-29,2015,29,Monday,June,Atlantic Southeast Airlines,N15555,4527,11h15,11h14,-1.0,7.0,1121.0,125.0,2.08,107.0,93.0,1.55,1254.0,7.0,13h01,-19.0,0.0,0.0,0,0,None,0.0,0.0,0.0,0.0,0.0,Indianapolis International Airport,Indianapolis,IN,Newark Liberty International Airport,Newark,NJ,Indianapolis-Newark

In [30]:
print("Dataset shape:", aviation_df.shape)

Dataset shape: (5819079, 39)

In [ ]:
# Count cancelled flights

num_cancelled = aviation_df['CANCELLED'].sum()
total_flights = len(aviation_df)
print(f"Number of cancelled flights: {num_cancelled}")
print(f"Percentage of cancelled flights: {num_cancelled/total_flights*100:.2f}%")

Number of cancelled flights: 89884
Percentage of cancelled flights: 1.54%

In [35]:
# Count diverted flights

num_diverted = aviation_df['DIVERTED'].sum()
total_flights = len(aviation_df)
print(f"Number of diverted flights: {num_diverted}")
print(f"Percentage of diverted flights: {num_diverted/total_flights*100:.2f}%")

Number of diverted flights: 15187
Percentage of diverted flights: 0.26%

In [31]:
print("Missing values per column:\n", aviation_df.isna().sum().sort_values(ascending=False).head(15))

Missing values per column:
 EXTREME_DELAY          105071
DELAYED                105071
ARRIVAL_DELAY          105071
ARRIVAL_TIME           105071
DEPARTURE_TIME          89884
WHEELS_ON               89884
AIR_TIME_HOURS          89884
AIR_TIME                89884
ELAPSED_TIME            89884
TAXI_IN                 89884
LATE_AIRCRAFT_DELAY         0
AIRLINE_DELAY               0
CANCELLED                   0
AIR_SYSTEM_DELAY            0
CANCELLATION_REASON         0
dtype: int64

In [32]:
# Saving the aviation dataframe in the data carpet

aviation_df.to_csv('../data/joint_dataset_cleaning.csv', index=False)